services:
  - type: web
    name: cdgproducaoback
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /api/auth/verificar
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: cdgproducaoback
          property: port
      - key: DATABASE_PATH
        value: /tmp/database.sqlite
      - key: API_HOST
        value: 0.0.0.0